name: MSVC MSYS2
description: Sets up an MSYS2 environment that uses the MSVC compiler.
author: Cyderize
inputs:
  clean-path:
    description: Whether or not the PATH should be cleaned to only allow MSYS2 and MSVC tools
    default: true
  use-msvc:
    description: Whether or not to run VsDevCmd.bat to setup MSVC environment
    default: true
  shell-name:
    description: This name can be used with the shell of run steps to use MSYS2
    default: msys2
  update:
    description: Whether or not MSYS2 should be updated
    default: true
  version:
    description: Version of MSYS2 to install (can also be `latest`, or `included` for built-in MSYS2)
    default: latest
runs:
  using: node12
  main: dist/index.js
