name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check build
        run: |
          npm install
          npm run all

  test:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [latest, included]
        update: [true, false]
        clean-path: [true, false]
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSVC-MSYS2
        uses: ./
        with:
          clean-path: ${{ matrix.clean-path }}
          shell-name: msys2
          update: ${{ matrix.update }}
          version: ${{ matrix.version }}
      - name: Run script using MSYS2
        run: |
          echo "Hello from MSYS2!"
          echo "----------"
          pacman -Q
          echo "----------"
          printenv
        shell: msys2 {0}
